export const siteConfig = {
  name: "Diego Alonso Valer Vilchez",
  shortName: "Diego Valer",
  title: "Business Student & Emerging Leader",
  description: "Diego Alonso Valer Vilchez — IBA Student at Constructor University, Bremen. Leadership, International Business, and Strategy.",

  colors: {
    primaryDark: "#1a0a0f",
    primary: "#2d1520",
    primaryLight: "#4a2035",
    accent: "#c9a96e",
    surface: "#0f0a0c",
    surfaceLight: "#f5f0eb",
  },

  tagline: "Building bridges between continents and opportunities.",

  stats: [
    { value: "3", label: "Countries" },
    { value: "4", label: "Languages" },
    { value: "20", label: "Students Mentored" },
    { value: "C2", label: "English" },
  ],

  heroImages: [
    "gallery/hero/img-20241222-wa0022.jpg",
    "gallery/hero/img-20251204-wa0008.jpg",
  ],

  social: {
    email: "Diego.valer.vilchez@gmail.com",
    linkedin: "https://www.linkedin.com/in/diego-valer-vilchez-01aa70242",
    whatsapp: "+4915224228675",
  },

  about: {
    intro: "I'm a 19-year-old Peruvian business student who crossed the Atlantic to pursue my passion for international business at Constructor University in Bremen, Germany.",
    body: "From leading CAS community projects in Lima to being recognized as the best teacher at a university summer camp in Germany, I've always believed that true leadership means lifting others up. As CFO of a student organization, academic tutor with an 85% student success rate, and team leader of 5 startup projects with perfect grades — I don't just study business, I practice it every day.",
    closing: "Currently pursuing my IBA degree with focus on Microeconomics, International Business, and Data Science. Accepted for an exchange semester at Yonsei University in Seoul, South Korea. Open to opportunities in consulting, strategy, and international business development.",
  },

  journey: [
    { year: "2006", place: "Lima, Peru", flag: "\u{1F1F5}\u{1F1EA}", event: "Born & raised" },
    { year: "2022", place: "Lima, Peru", flag: "\u{1F1F5}\u{1F1EA}", event: "San Agust\u00EDn \u2014 GPA 17.32, SAT 1240" },
    { year: "2023", place: "Lima, Peru", flag: "\u{1F1F5}\u{1F1EA}", event: "Universidad de Lima \u2014 Business Admin" },
    { year: "2024", place: "Bremen, Germany", flag: "\u{1F1E9}\u{1F1EA}", event: "Constructor University \u2014 IBA Bachelor" },
    { year: "2026", place: "Seoul, South Korea", flag: "\u{1F1F0}\u{1F1F7}", event: "Yonsei University \u2014 Exchange Semester" },
  ],

  education: [
    {
      school: "Constructor University",
      location: "Bremen, Germany",
      flag: "\u{1F1E9}\u{1F1EA}",
      degree: "IBA, Bachelor's Degree",
      dateRange: "Sep 2024 \u2013 Jun 2027",
      gpa: "GPA: 2.06",
      coursework: ["Microeconomy", "International Business", "Data Science"],
      images: ["gallery/constructor-uni/uni-2.jpg", "gallery/constructor-uni/uni-3.jpg", "gallery/constructor-uni/uni-4.jpg", "gallery/constructor-uni/uni-5.jpg"],
    },
    {
      school: "Yonsei University",
      location: "Seoul, South Korea",
      flag: "\u{1F1F0}\u{1F1F7}",
      degree: "Exchange Semester \u2014 International Business",
      dateRange: "2026",
      gpa: "Upcoming",
      coursework: ["International Business", "Asian Markets", "Global Strategy"],
      images: [],
    },
    {
      school: "Universidad de Lima",
      location: "Lima, Peru",
      flag: "\u{1F1F5}\u{1F1EA}",
      degree: "Business Administration",
      dateRange: "Mar 2023 \u2013 May 2024",
      gpa: "GPA: 17/20",
      coursework: ["Accountability", "Finance", "International Relations"],
      images: [],
    },
    {
      school: "Colegio San Agust\u00EDn de Lima",
      location: "Lima, Peru",
      flag: "\u{1F1F5}\u{1F1EA}",
      degree: "IBA Certificate in Business Administration",
      dateRange: "Mar 2011 \u2013 Dec 2022",
      gpa: "GPA: 17.32/20 \u00B7 SAT: 1240/1600",
      coursework: ["Math", "Business Administration"],
      images: ["gallery/school/school-1.jpg", "gallery/school/school-2.jpg", "gallery/school/school-3.jpg"],
    },
  ],

  leadership: [
    {
      number: "01",
      icon: "\u{1F3C6}",
      title: "Best Teacher Award",
      role: "Summer Camp Teacher: Investment & Entrepreneurship",
      org: "Constructor University",
      period: "Sep \u2013 Dec 2025",
      description: "Designed and delivered courses and exams from the ground up. Recognized as the best teacher for quality of instruction and leadership.",
      skills: ["Curriculum Design", "Public Speaking", "Investment Analysis", "Entrepreneurship"],
      details: "Created comprehensive course materials covering investment fundamentals and entrepreneurial thinking for university summer camp participants. Developed exams and evaluation criteria from scratch. Received the highest student evaluation scores among all instructors.",
      images: ["gallery/summercamp/summercamp-1.jpg", "gallery/summercamp/summercamp-2.jpg", "gallery/summercamp/summercamp-3.jpg", "gallery/summercamp/summercamp-4.jpg", "gallery/summercamp/summercamp-5.jpg"],
    },
    {
      number: "02",
      icon: "\u{1F4B0}",
      title: "Chief Financial Officer",
      role: "Student Organization \u2014 Orchestra",
      org: "Constructor University",
      period: "Jun 2025 \u2013 Present",
      description: "Managing costs, instrument rentals, and event planning. Handling ticket sales, budgets, and financial operations for campus events.",
      skills: ["Budget Management", "Financial Planning", "Event Logistics", "Team Coordination"],
      details: "Oversee the complete financial operations of the student organization including budget allocation, expense tracking, and revenue management from ticket sales. Coordinate instrument rentals and logistics for campus-wide events. Also an active member of the university orchestra as a saxophone player.",
      images: ["gallery/orchestra/orchestra-1.jpg", "gallery/orchestra/orchestra-2.jpg", "gallery/orchestra/orchestra-3.jpg"],
    },
    {
      number: "03",
      icon: "\u{1F4CA}",
      title: "Academic Tutor \u2014 85% Success Rate",
      role: "Economics & Project Management",
      org: "Constructor University",
      period: "Sep \u2013 Dec 2025",
      description: "Helped 20 international students with Micro/Macroeconomics and International Business. 17 out of 20 passed with excellent scores.",
      skills: ["Microeconomics", "Macroeconomics", "Teaching", "Mentoring"],
      details: "Provided one-on-one and group tutoring sessions for 20 international students struggling with economics courses. Developed custom study materials and practice exams. Achieved an 85% success rate \u2014 17 out of 20 students passed with strong grades.",
      images: ["gallery/leadership/leadership-1.jpg", "gallery/leadership/leadership-2.jpg"],
    },
    {
      number: "04",
      icon: "\u{1F3AF}",
      title: "Team Leader \u2014 Perfect Grades",
      role: "5 Startup & Marketing Research Projects",
      org: "Constructor University",
      period: "Sep \u2013 Dec 2025",
      description: "Led 5 different group projects related to startups and marketing research. Successfully achieved a perfect grade in all projects.",
      skills: ["Project Management", "Marketing Research", "Startup Strategy", "Team Leadership"],
      details: "Directed multicultural teams across 5 distinct academic projects spanning startup development and marketing research. Managed timelines, delegated tasks, and ensured high-quality deliverables. Every project received the highest possible grade.",
      images: [],
    },
    {
      number: "05",
      icon: "\u{1F52C}",
      title: "Agro-Export Research",
      role: "Pre-feasibility Study: South America \u2192 Europe",
      org: "Constructor University",
      period: "Jun \u2013 Nov 2025",
      description: "Pre-feasibility project for the agro-export of products from South America to Europe, presented at the XII competition for feasibility projects.",
      skills: ["Market Research", "Data Analysis", "International Trade", "Academic Writing"],
      details: "Conducted a comprehensive pre-feasibility study analyzing the potential for agro-export trade routes between South America and Europe. Presented findings at the XII competition for feasibility projects, evaluating market demand, logistics, and regulatory frameworks.",
      images: [],
    },
    {
      number: "06",
      icon: "\u{1F91D}",
      title: "Community Service Leader",
      role: "CAS Projects \u2014 Creativity, Activity & Service",
      org: "Colegio San Agust\u00EDn, Lima",
      period: "Mar 2018 \u2013 Nov 2022",
      description: "Managed student working groups and fundraising activities to help underprivileged children. Taught basic Mathematics and English to children of limited resources.",
      skills: ["Community Outreach", "Fundraising", "Teaching", "Social Impact"],
      details: "Led multiple community service initiatives over 4 years as part of the CAS program. Organized fundraising events and managed teams of student volunteers. Personally taught Mathematics and English classes to children from underprivileged backgrounds.",
      images: ["gallery/cas/cas-1.jpg", "gallery/cas/cas-2.jpg"],
    },
  ],

  projects: [
    {
      title: "Marketing Report: AdVibe",
      subtitle: "A Critical Analysis of Pret a Manger's failed attempt to enter the Shanghai market in 2018",
      icon: "\u{1F4C8}",
      course: "Marketing",
      file: "projects/marketing-report-advibe.pdf",
    },
    {
      title: "PetitLuxe Express",
      subtitle: "Master Project Document \u2014 Fast Luxury for China",
      icon: "\u{1F4CB}",
      course: "Project Management",
      file: "projects/petitluxe-express-project.pdf",
    },
  ],

  skills: {
    languages: [
      { name: "Spanish", level: "Native", flag: "\u{1F1EA}\u{1F1F8}" },
      { name: "English", level: "C2 Advanced", flag: "\u{1F1EC}\u{1F1E7}" },
      { name: "German", level: "A2 Intermediate", flag: "\u{1F1E9}\u{1F1EA}" },
      { name: "Portuguese", level: "A2 Intermediate", flag: "\u{1F1E7}\u{1F1F7}" },
    ],
    technical: ["Python", "R-Studio", "Overleaf", "Data Science", "PowerPoint", "Excel", "Canva", "Linux"],
    professional: ["Business Development", "Strategic Communication", "International Relations", "Event Management", "Analytics", "Project Leadership"],
    interests: [
      { name: "Saxophone", icon: "\u{1F3B7}" },
      { name: "Chess", icon: "\u265F\uFE0F" },
      { name: "Catan", icon: "\u{1F3B2}" },
      { name: "Walking", icon: "\u{1F6B6}" },
    ],
  },
};
